version: '3'
services:
  chat-app:
    build: .
    ports:
      - "5000:5000"
    environment:
      MONGO_URI: "mongodb://mongo:27017/chat"
      JWT_SECRET: "your_jwt_secret"
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
